config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :photos
  resources :posts
  resources :tips
  resources :contacts, only: [:new, :create]

  get 'getpins/index' # get the pins for the map
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/map', to: 'content#map', as: :map #=> map_path
  get '/subscribe', to: 'content#subscribe', as: :subscribe #=> subscribe_path
  match '/contact' => "contacts#new", via: [:get, :post], as: :contact
  get '/locations', to: 'content#locations', as: :locations

  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
	extend FriendlyId
	friendly_id :title, use: :slugged
  # searchkick
  has_and_belongs_to_many :photos

  def should_generate_new_friendly_id?
    title_changed?
  end

  before_save -> do
    # Allow override of the published date, otherwise use the current date
    if !self.published_date.present?
      self.published_date = self.created_at
    end

    # Attach Flickr photos to this post if specified as flickr_album
    begin
      if self.flickr_album.present?
        Rails.logger.info "Processing Flickr album: #{self.flickr_album}"
        photoset_id = self.flickr_album
        
        # Initialize Flickr with authentication
        require 'oauth'
        require 'json'
        
        consumer = OAuth::Consumer.new(
          ENV['FLICKR_API_KEY'],
          ENV['FLICKR_SHARED_SECRET'],
          site: 'https://www.flickr.com',
          request_token_path: '/services/oauth/request_token',
          access_token_path: '/services/oauth/access_token',
          authorize_path: '/services/oauth/authorize'
        )
        
        access_token = OAuth::AccessToken.new(
          consumer,
          ENV['FLICKR_ACCESS_TOKEN'],
          ENV['FLICKR_ACCESS_SECRET']
        )
        
        # Get photoset info first to verify access
        begin
          response = access_token.get("https://api.flickr.com/services/rest/?method=flickr.photosets.getInfo&photoset_id=#{photoset_id}&format=json&nojsoncallback=1")
          photoset_info = JSON.parse(response.body)
          
          if photoset_info['stat'] == 'ok'
            Rails.logger.info "Found photoset: #{photoset_info['photoset']['title']['_content']}"
            
            # Get photos from the photoset
            begin
              response = access_token.get("https://api.flickr.com/services/rest/?method=flickr.photosets.getPhotos&photoset_id=#{photoset_id}&format=json&nojsoncallback=1")
              photos_data = JSON.parse(response.body)
              
              if photos_data['stat'] == 'ok'
                Rails.logger.info "Found #{photos_data['photoset']['photo'].size} photos in album"
                
                photos_data['photoset']['photo'].each do |photo_data|
                  photo_id = photo_data['id']
                  Rails.logger.info "Processing photo: #{photo_id}"
                  
                  if (Photo.where(:flickr_id => photo_id).count == 0)
                    Rails.logger.info "Creating new photo record for #{photo_id}"
                    
                    # Get photo info
                    response = access_token.get("https://api.flickr.com/services/rest/?method=flickr.photos.getInfo&photo_id=#{photo_id}&format=json&nojsoncallback=1")
                    photo_info = JSON.parse(response.body)
                    
                    if photo_info['stat'] == 'ok'
                      date_taken = photo_info['photo']['dates']['taken']
                      title = photo_info['photo']['title']['_content']
                      description = photo_info['photo']['description']['_content']
                      
                      # Get photo sizes
                      response = access_token.get("https://api.flickr.com/services/rest/?method=flickr.photos.getSizes&photo_id=#{photo_id}&format=json&nojsoncallback=1")
                      sizes_data = JSON.parse(response.body)
                      
                      thumb = ''
                      small = ''
                      medium = ''
                      large = ''
                      
                      if sizes_data['stat'] == 'ok'
                        sizes_data['sizes']['size'].each do |size|
                          case size['label']
                          when 'Thumbnail'
                            thumb = size['source']
                          when 'Small'
                            small = size['source']
                          when 'Medium'
                            medium = size['source']
                          when 'Large'
                            large = size['source']
                          end
                        end
                        
                        # Create the photo record
                        photo = Photo.create!(
                          flickr_id: photo_id,
                          title: title,
                          description: description,
                          date_taken: date_taken,
                          thumb: thumb,
                          small: small,
                          medium: medium,
                          large: large
                        )
                        
                        self.photos << photo
                      end
                    end
                  end
                end
              else
                Rails.logger.error "Error getting photos from photoset: #{photos_data['message']}"
              end
            rescue => e
              Rails.logger.error "Error getting photos from photoset: #{e.message}"
            end
          else
            Rails.logger.error "Error getting photoset info: #{photoset_info['message']}"
          end
        rescue => e
          Rails.logger.error "Error getting photoset info: #{e.message}"
        end
      end
    rescue => e
      Rails.logger.error "Error processing Flickr album: #{e.message}"
      # Don't raise the error, allow the post to save
    end
  end

	geocoded_by :placename
	reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.city = geo.city
      obj.state = geo.state
      obj.country = geo.country
    end
  end
  after_validation :geocode, if: :placename_changed?
  after_validation :reverse_geocode, if: :placename_changed?

  def next
    Post.where("published_date > ?", published_date).where("status = 'published'").order("published_date ASC").first
  end

  def previous
    Post.where("published_date < ?", published_date).where("status = 'published'").order("published_date DESC").first
  end

  def unique_photos
    photos.distinct.order(:sort)
  end

  def deduplicate_photos!
    # Get unique photo IDs while preserving order
    unique_photo_ids = photos.order(:sort).pluck(:id).uniq
    
    # Clear existing associations
    photos.clear
    
    # Re-add photos in order, ensuring no duplicates
    unique_photo_ids.each_with_index do |photo_id, index|
      photo = Photo.find(photo_id)
      photo.update(sort: index)
      photos << photo
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]

  include ActionView::Helpers::DateHelper

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = "Sorry, that post does not exist"
    redirect_to action: :index
  end

  def index
    # if params[:query].present?
    #   # Find posts using elastic search
    #   @posts = Post.where("status = 'published'").search(params[:query], page: params[:page], :per_page => 10)
    if params[:id].present?
      @post = Post.find(params[:id])
      redirect_to @post
      return
    elsif params[:api].present?
      @posts = Post.where("status = 'published'").order published_date: :desc
    else
      @posts = Post.paginate(:page => params[:page], :per_page => 4).order published_date: :desc
    end

    begin
      @header_image_url = @posts.where(status: "published").first.photos.order(:sort).first.large
    rescue
      @header_image_url = 'https://farm9.staticflickr.com/8026/7254508562_25fc4962e5_b.jpg'
    end

    respond_to do |format|
      format.html
      format.json {
        render :json =>
        @posts.to_json(
          :include => { :photos => { :only => [:id, :sort, :title, :small, :large] } },
          :only => [:id, :title, :content, :placename, :latitude, :longitude, :slug, :published_date]

        )}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.friendly.find(params[:id])
    @meta = @post.published_date ? "Posted #{time_ago_in_words(@post.published_date)} ago" : "Posted"
    if @post.city && @post.country
      @meta += " in #{@post.city}, #{@post.country}"
    end
    if @post.photos.count > 0
      @og_image = @post.photos.order(:sort).first.large
    end
    @og_title = @post.title

    respond_to do |format|
      format.html
      format.json {
        render :json =>
        @post.to_json(
          :include => { :photos => { :only => [:id, :sort, :title, :small, :large] } },
          :only => [:id, :title, :content, :placename, :latitude, :longitude, :slug, :published_date]

        )
      }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def by_location
    @posts = Post.where(status: 'published')
                .where.not(latitude: nil)
                .order(:country, :city)
    
    # Group posts by country and city
    @posts_by_location = @posts.group_by(&:country).transform_values do |country_posts|
      country_posts.group_by(&:city)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :placename, :published_date, :flickr_album, :status)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f|
  .container.top-50
    .form-group
      = f.input :title
      = f.text_area :content, :class => "tinymce", :rows => 20, :cols => 120
      = f.input :placename
      = f.input :published_date, :start_year => 2001
      = f.input :flickr_album
      = f.select :status, ['draft', 'published']
    = f.button :submit
    = tinymce

app/views/posts/by_location.html.haml
.container
  .row
    .col-md-12
      %h1 Posts by Location
      %p Browse all posts organized by country and city

  - @posts_by_location.each do |country, cities|
    .row.mb-4
      .col-md-12
        %h2.mb-3= country || "Unknown Country"
        
        - cities.each do |city, posts|
          .city-section.mb-4
            %h3.mb-3= city || "Unknown City"
            
            .row
              - posts.each do |post|
                .col-md-4.mb-4
                  .card.h-100
                    - if post.photos.any?
                      = link_to post do
                        %img.card-img-top{src: post.photos.first.small, alt: "#{post.title} thumbnail"}
                    .card-body
                      %h5.card-title= link_to post.title, post
                      %p.card-text
                        %small.text-muted= post.published_date.strftime("%B %d, %Y")
                    .card-footer
                      = link_to "Read more", post, class: "btn btn-primary" 

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post

-if @post.photos.count > 0
  .container.mt-4
    .row
      .col-md-12
        %h4.mb-3 Photos
        .table-responsive
          %table.table.table-hover
            %thead
              %tr
                %th{style: "width: 150px"} Thumbnail
                %th Title
                %th{style: "width: 100px"} Actions
            %tbody.sortable
              -@post.photos.order(:sort).each_with_sortable_id do |photo, sortable_id|
                %tr{:id => sortable_id}
                  %td
                    %img.img-thumbnail{:src => photo.small, :width => "140"}/
                  %td.editable-cell
                    .editable-title{data: {photo_id: photo.id}}
                      = photo.title
                  %td
                    = link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm'

.container.mt-4
  .row
    .col-md-12
      = link_to 'Show', @post, class: 'btn btn-secondary'
      = link_to 'Back', posts_path, class: 'btn btn-link ml-2'

:javascript
  $(document).ready(function() {
    $(document).on('click', '.editable-cell:not(.editing)', function(e) {
      e.stopPropagation();
      const $cell = $(this);
      const $title = $cell.find('.editable-title');
      const currentTitle = $title.text().trim();
      const photoId = $title.data('photo-id');
      
      $cell.addClass('editing');
      $title.html(`
        <input type="text" value="${currentTitle}" class="form-control form-control-sm">
      `);
      
      const $input = $cell.find('input');
      $input.focus();
      
      // Store original title for cancel
      $cell.data('original-title', currentTitle);
      
      $input.on('keydown', function(e) {
        if (e.key === 'Enter') {
          e.preventDefault();
          const newTitle = $input.val();
          
          $.ajax({
            url: `/photos/${photoId}`,
            method: 'PATCH',
            data: { photo: { title: newTitle } },
            dataType: 'json',
            headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content'),
              'Accept': 'application/json'
            },
            success: function() {
              $cell.removeClass('editing');
              $title.text(newTitle);
            },
            error: function() {
              alert('Failed to update title');
              $cell.removeClass('editing');
              $title.text($cell.data('original-title'));
            }
          });
        } else if (e.key === 'Escape') {
          e.preventDefault();
          $cell.removeClass('editing');
          $title.text($cell.data('original-title'));
        }
      });
      
      // Handle click outside to cancel
      $(document).on('click.editable-cell', function(e) {
        if (!$(e.target).closest('.editable-cell').length) {
          $cell.removeClass('editing');
          $title.text($cell.data('original-title'));
          $(document).off('click.editable-cell');
        }
      });
    });
  });

app/views/posts/index.html.haml
/ Page Header
%header.masthead{:style => "background-image: url('#{@header_image_url}')", :role => "img", "aria-label" => "Travel blog header image"}
  .container
    .row
      .col-lg-8.col-md-10.mx-auto
        .site-heading
          %h1 Steve and Glo's travel blog
          %span.subheading exploring the world since 2001

/ Main Content
.container
  .row
    .col-12
      - @posts.each.with_index do |post, idx|
        - if post.status == 'published' || user_signed_in?
          .row.mt-5
            -if idx == 0 and post.latitude?
              .col-md-8.col-12
                .post-preview
                  %h2.post-title
                    =link_to post.title, post
                  -if post.city && post.country
                    %span.meta= post.published_date ? "Posted #{time_ago_in_words(post.published_date)} ago in #{post.city}, #{post.country}" : "Posted in #{post.city}, #{post.country}"
                  - else
                    %span.meta= post.published_date ? "Posted #{time_ago_in_words(post.published_date)} ago" : "Posted"
                  - if post.status == 'draft'
                    %span.meta.draft= "(draft)"
                  %p.post-subtitle
                    =sanitize(post.content)
              = content_tag 'div', '', class: 'col-md-4 col-12 post_id', id: 'minimapdiv', data: {id: post.id, latitude: post.latitude, longitude: post.longitude}, role: "region", "aria-label" => "Map showing location for #{post.title}" do
                #map.minimap.col-12.d-none.d-md-block{"aria-label" => "Interactive map"}
                %span#fullscreen.d-none.d-md-block= link_to "view full screen", map_path(:post => post.id), "aria-label" => "Open full screen map for #{post.title}"

            - else
              .col-12
                .post-preview
                  %h2.post-title
                    =link_to post.title, post
                  -if post.city && post.country
                    %span.meta= post.published_date ? "Posted #{time_ago_in_words(post.published_date)} ago in #{post.city}, #{post.country}" : "Posted in #{post.city}, #{post.country}"
                  - else
                    %span.meta= post.published_date ? "Posted #{time_ago_in_words(post.published_date)} ago" : "Posted"
                  - if post.status == 'draft'
                    %span.meta.draft= "(draft)"
                  %p.post-subtitle
                    =sanitize(post.content)

          - if post.photos.count > 0
            .row.mt-5{"role" => "region", "aria-label" => "Photo gallery for #{post.title}"}
              .col-12
                %p.sr-only{"aria-live" => "polite"} Gallery contains #{post.unique_photos.offset(1).count} photos
                .pswp-gallery{"itemscope" => "", "itemtype" => "http://schema.org/ImageGallery"}
                  .row
                    - post.unique_photos.each do |photo|
                      .col-md-4
                        %figure
                          %a{"href" => photo.large, "itemprop" => "contentUrl", "target" => "_blank"}
                            %img.image.img-fluid{:alt => "#{photo.title} - #{post.title} photo gallery", :src => photo.medium}
                          - if not photo.title.include?("jpg")
                            %figcaption{:id => "photo-desc-#{photo.id}"}= photo.title


  #hr
  .container.pt-3
    .row.justify-content-center
      .col-auto
        %nav
          = will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, class: 'pagination'

  %br/
  - if user_signed_in?
    = link_to 'New Post', new_post_path, class: 'btn btn-primary'

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
.container
	.row
		.col-md-12
			= link_to 'Back', posts_path

app/views/posts/show.html.haml
/ Page Header
= content_tag 'div', '', class: 'container-fluid top-50 post_id', id: 'post_id', data: {id: @post.id, latitude: @post.latitude, longitude: @post.longitude}
-if @post.photos.count > 0
	%header.masthead{:style => "background-image: url(#{@post.unique_photos.first.large})", :role => "img", "aria-label" => "Header image for post: #{@post.title}"}
		.container
			.row
				.col-lg-8.col-md-10.mx-auto
					.post-heading
						%h1= @post.title
						%span.meta=@meta
						- if @post.status == 'draft'
							%span.meta.draft= "(draft)"



%article
	.container
		.row.mt-5
			.col-md-12
				- if user_signed_in?
					.row
						.col-md-12
							= link_to 'Edit', edit_post_path(@post)
				.row
					-if @post.content.present?
						-if @post.latitude.present?
							#content.col-md-8
								= sanitize @post.content
							= content_tag 'div', '', class: 'col-md-4 post_id', id: 'minimapdiv', data: {id: @post.id, latitude: @post.latitude, longitude: @post.longitude}, role: "region", "aria-label" => "Map showing location for #{@post.title}" do
								#map.minimap.col-md-12.d-none.d-md-block{"aria-label" => "Interactive map"}
								%span#fullscreen.d-none.d-md-block= link_to "view full screen", map_path(:post => @post.id), "aria-label" => "Open full screen map for #{@post.title}"
						-else
							#content.col-md-12
								= sanitize @post.content
					-else
						.col-md-12
							%p No content available for this post.

		-if @post.previous || @post.next
			.row.pagination.top-50
				.col-md-12
					%nav
						%ul.pagination.justify-content-center
							-if @post.previous
								%li.page-item
									=link_to "Previous post: #{@post.previous.title}", @post.previous, :class => "page-link"
							-if @post.next
								%li.page-item
									=link_to "Next post: #{@post.next.title}", @post.next, :class => "page-link"
		- if @post.photos.count > 0
			.row.lightboxpics.mt-5{"role" => "region", "aria-label" => "Photo gallery for #{@post.title}"}
				.col-md-12
					%p.sr-only{"aria-live" => "polite"} Gallery contains #{@post.unique_photos.offset(1).count} photos
				- @post.unique_photos.offset(1).each.with_index do |photo, index|
					.col-md-4
						-if user_signed_in?
							= link_to photo_path(photo), method: :delete, class: "float-end", data: {confirm: "Are you sure you want to delete this photo?"}, "aria-label" => "Delete photo: #{photo.title}" do
								%i.fa.fa-times{"aria-hidden" => "true"}
						%figure
							%a.image-link{"data-lightbox" => "#{@post.title}", "data-title" => "#{photo.title}", :href => "#{photo.large}", "aria-label" => "View larger version of #{photo.title} (photo #{index + 1} of #{@post.unique_photos.offset(1).count})", :tabindex => "0", "aria-describedby" => "photo-desc-#{photo.id}"}
								%img.image{:alt => "#{photo.title} - #{@post.title} photo gallery", :src => "#{photo.large}", :class => "lightbox-thumb mx-auto d-block"}
							-if not photo.title.include? "jpg"
								%figcaption{:id => "photo-desc-#{photo.id}"}= "#{photo.title}"


-if @post.previous || @post.next
	.container.top-50
		.row.pagination
			.col-md-12
				%nav
					%ul.pagination.justify-content-center
						-if @post.previous
							%li.page-item
								=link_to "<< #{@post.previous.title}", @post.previous, :class => "page-link"
						%li.page-item
							=link_to 'All posts', posts_path, :class => "page-link"
						-if @post.next
							%li.page-item
								=link_to "#{@post.next.title} >>", @post.next, :class => "page-link"

.container
	.row
		.col-md-12
			- if user_signed_in?
				= link_to 'Edit', edit_post_path(@post)
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }