config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :photos
  resources :posts
  resources :tips
  resources :contacts, only: [:new, :create]

  get 'getpins/index' # get the pins for the map
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/map', to: 'content#map', as: :map #=> map_path
  get '/subscribe', to: 'content#subscribe', as: :subscribe #=> subscribe_path
  match '/contact' => "contacts#new", via: [:get, :post], as: :contact
  get '/locations', to: 'content#locations', as: :locations

  root to: "posts#index"
end

app/models/tip.rb
class Tip < ApplicationRecord
  validates :title, presence: true
	extend FriendlyId
	friendly_id :title, use: :slugged
  # searchkick

  def should_generate_new_friendly_id?
    title_changed?
  end

  before_save -> do
  end

  def next
    Tip.where("created_at > ?", created_at).order("created_at ASC").first
  end

  def previous
    Tip.where("created_at < ?", created_at).order("created_at DESC").first
  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]

  include ActionView::Helpers::DateHelper

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = "Sorry, that tip does not exist"
    redirect_to action: :index
  end

  def index
    if params[:id].present?
      @tip = Tip.find(params[:id])
      redirect_to @tip
      return
    elsif params[:category].present?
      @tips = Tip.where(category: params[:category]).paginate(:page => params[:page], :per_page => 3).order created_at: :desc
    else
      @tips = Tip.paginate(:page => params[:page], :per_page => 3).order created_at: :desc
    end
    @header_image_url = 'https://farm9.staticflickr.com/8026/7254508562_25fc4962e5_b.jpg'

    respond_to do |format|
      format.html
    end
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
    @tip = Tip.friendly.find(params[:id])
    @meta = "Published #{time_ago_in_words(@tip.created_at)} ago"
    if @tip.category.present?
      @meta += " in " + @tip.category.titlecase
    end
    @og_title = @tip.title
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:title, :content, :created_at, :category)
    end

end

app/views/tips/_form.html.haml
= simple_form_for(@tip, html: { class: 'form-horizontal' }) do |f|
  .container.top-50
    .form-group
      = f.input :title
      = f.text_area :content, :class => "tinymce", :rows => 20, :cols => 120
      = f.input :category, :collection => %w[money kids gadgets]
    = f.button :submit
    = tinymce

app/views/tips/edit.html.haml
%h1 Editing Tip
= render 'form', tip: @tip

.container
	.row
		.col-md-12
			= link_to 'Show', @tip
			#{link_to 'Back', tips_path}

app/views/tips/index.html.haml
.container
  .row.top-100
    .col-lg-8.col-md-10.mx-auto
      .site-heading.center
        %h2 Steve and Glo's travel tips
        %span.subheading Useful stuff we've learnt on the road
  %hr

.row
  .col-md-12.hidden-sm.hidden-xs.center
    =link_to tips_path(category: "money") do
      %span.btn
        %i.fa.fa-dollar
        = "money"
    =link_to tips_path(category: "kids") do
      %span.btn
        %i.fa.fa-child
        = "kids"
    =link_to tips_path(category: "gadgets") do
      %span.btn
        %i.fa.fa-camera
        = "gadgets"
    =link_to tips_path do
      %span.btn
        %i.fa.fa-times
        clear

/ Main Content
.container
  .row
    .col-md-12
      - @tips.each.with_index do |tip, idx|
        .row.top-50
          .col-md-10.mx-auto
            .tip-preview
              %h2.tip-title
                =link_to tip.title, tip
              %span.meta= "Posted #{time_ago_in_words(tip.created_at)} ago"
              %p.tip-subtitle
                =sanitize(tip.content)

  #hr
  .row
    .col-lg-8.col-md-10.mx-auto
      = will_paginate @tips, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

  %br/
  - if user_signed_in?
    = link_to 'New Tip', new_tip_path

app/views/tips/new.html.haml
%h1 New Tip
= render 'form', tip: @tip
.container
	.row
		.col-md-12
			= link_to 'Back', tips_path

app/views/tips/show.html.haml
/ Page Header
.container-fluid.top-50
	%header.empty
		.container
			.row
				.col-lg-8.col-md-10.mx-auto
					.tip-heading
						%h1= @tip.title
						%span.meta=@meta

	%article
		.container
			- if user_signed_in?
				.row
					= link_to 'Edit', edit_tip_path(@tip)
			.row
				.col-lg-8.col-md-10.mx-auto
					= sanitize @tip.content

	-if @tip.previous || @tip.next
		.container.top-50
			.row.pagination
				.col-md-12
					#nav.pagination
						#ul.pagination
							-if @tip.previous
								#li.page-item
									=link_to "<< #{@tip.previous.title}", @tip.previous, :class => "page-link"
							#li.page-item
								=link_to 'All tips', tips_path, :class => "page-link"
							-if @tip.next
								#li.page-item
									=link_to "#{@tip.next.title} >>", @tip.next, :class => "page-link"

	.container
		.row
			.col-md-12
				- if user_signed_in?
					= link_to 'Edit', edit_tip_path(@tip)
					= link_to "Delete", tip_path(@tip), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }