config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :photos
  resources :posts
  resources :tips
  resources :contacts, only: [:new, :create]

  get 'getpins/index' # get the pins for the map
  get '/about', to: 'content#about', as: :about #=> about_path
  get '/map', to: 'content#map', as: :map #=> map_path
  get '/subscribe', to: 'content#subscribe', as: :subscribe #=> subscribe_path
  match '/contact' => "contacts#new", via: [:get, :post], as: :contact
  get '/locations', to: 'content#locations', as: :locations

  root to: "posts#index"
end

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-lg-8.col-md-10.mx-auto
        %hr
        %p.copyright.text-muted= "Copyright © Stephen Lead and Gloria Tong, #{Time.current.year}"

        %ul.list-inline.text-center
          %li.list-inline-item.footer-link
            =link_to "Subscribe", subscribe_path
        

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark#mainNav{"aria-label" => "Main navigation", :role => "navigation"}
  .container
    = link_to "Steve and Glo's travel blog", root_path, class: "navbar-brand"
    %button.navbar-toggler{
        "aria-controls" => "navbarCollapse",
        "aria-expanded" => "false",
        "aria-label" => "Toggle navigation",
        "data-bs-toggle" => "collapse",      # ✅ Bootstrap 5 syntax
        "data-bs-target" => "#navbarCollapse", # ✅ Bootstrap 5 syntax
        :type => "button"
    }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarCollapse
      %ul.navbar-nav.ms-auto
        %li.nav-item
          = link_to "Posts", posts_path, class: "nav-link"
        %li.nav-item
          = link_to "Countries", locations_path, class: "nav-link"
        %li.nav-item
          = link_to "Map", map_path, class: "nav-link"
        %li.nav-item
          = link_to "Subscribe", subscribe_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to "New Post", new_post_path, class: "nav-link"

app/views/layouts/_notifications.haml
.notifications
  - if notice
    #notice_wrapper
      .alert.alert-dismissible.fade.show{role: "alert"}
        = notice
        %button.btn-close{type: "button", "data-bs-dismiss": "alert", "aria-label": "Close"}
  - elsif alert
    #alert_wrapper
      .alert.alert-dismissible.fade.show{role: "alert"}
        = alert
        %button.btn-close{type: "button", "data-bs-dismiss": "alert", "aria-label": "Close"}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "Steve and Glo's travel blog", :name => "description"}/
    %meta{:content => "Stephen Lead", :name => "author"}/
    %meta{'name' => 'contact', :content => 'http://www.stephenlead.com'}
    %meta{'property' => "og:title", :content => og_title}
    %meta{'property' => "og:description", :content => "Steve and Glo's travel blog"}
    %meta{'property' => "og:url", :content => request.original_url}
    %meta{'property' => "og:type", :content => "website"}
    %meta{'property' => "og:image", :content => og_image}
    %meta{'property' => "og:image:width", :content => "1024"}
    %meta{'property' => "og:image:height", :content => "600"}
    %meta{'name' => 'twitter:card', :content => 'summary_large_image'}
    %meta{'name' => 'twitter:site', :content => '@stephenlead'}
    %meta{'name' => 'twitter:image', :content => og_image}
    %meta{'name' => 'twitter:description', :content => "Steve and Glo's travel blog"}

    %title Travels with Steve and Glo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    / Custom fonts for this template
    %link{:href => "https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}/
    = favicon_link_tag 'favicon.ico'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:async => true, :src => "https://www.googletagmanager.com/gtag/js?id=G-VV6R9TGNQZ"}
    :javascript
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-VV6R9TGNQZ');

  %body
    %a.sr-only.sr-only-focusable{:href => "#main-content"} Skip to main content
    =render 'layouts/nav'
    =render 'layouts/notifications'
    %main{:id => "main-content", :role => "main"}
      = yield
    %footer{:role => "contentinfo"}
      =render 'layouts/footer'
    
    / Root element of PhotoSwipe. Must have class pswp.
    .pswp{:tabindex => "-1", :role => "dialog", :aria => {:hidden => "true"}}
      .pswp__bg
      .pswp__scroll-wrap
        .pswp__container
          .pswp__item
          .pswp__item
          .pswp__item
        .pswp__ui.pswp__ui--hidden
          .pswp__top-bar
            .pswp__counter
            %button.pswp__button.pswp__button--close{:title => "Close (Esc)"}
            %button.pswp__button.pswp__button--share{:title => "Share"}
            %button.pswp__button.pswp__button--fs{:title => "Toggle fullscreen"}
            %button.pswp__button.pswp__button--zoom{:title => "Zoom in/out"}
            .pswp__preloader
              .pswp__preloader__icn
                .pswp__preloader__cut
                  .pswp__preloader__donut
          .pswp__share-modal.pswp__share-modal--hidden
            .pswp__share-tooltip
          %button.pswp__button.pswp__button--arrow--left{:title => "Previous (arrow left)"}
          %button.pswp__button.pswp__button--arrow--right{:title => "Next (arrow right)"}
          .pswp__caption
            .pswp__caption__center